services:
  - type: web
    name: prt-algorithm-app
    env: docker
    plan: free
    dockerfilePath: Dockerfile.combined
    envVars:
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: /PRT
    regions:
      - oregon
